# Tugas Besar 1 IF3270 Pembelajaran Mesin Feedforward Neural Network

|   NIM    |            NAMA            |
| :------: | :------------------------: |
| 13522037 |    Farhan Nafis Rayhan     |
| 13522091 | Raden Francisco Trianto B. |


## Import Dataset MNIST

In [1]:
import numpy as np
from sklearn.datasets import fetch_openml

X: np.ndarray  # input
y: np.ndarray  # target

# Load data from https://www.openml.org/search?type=data&sort=runs&id=554   
X, y = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False)

 
# MNIST: dataset of 28x28 pixel images of handwritten digits (0-9)
# Input: vector of 784 pixels (28x28)
# Target: number 0-9

In [2]:
X.shape, y.shape

((70000, 784), (70000,))

## Split First 250 data

In [14]:
X, y = X[:250], y[:250]

In [15]:
X, y

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array(['5', '0', '4', '1', '9', '2', '1', '3', '1', '4', '3', '5', '3',
        '6', '1', '7', '2', '8', '6', '9', '4', '0', '9', '1', '1', '2',
        '4', '3', '2', '7', '3', '8', '6', '9', '0', '5', '6', '0', '7',
        '6', '1', '8', '7', '9', '3', '9', '8', '5', '9', '3', '3', '0',
        '7', '4', '9', '8', '0', '9', '4', '1', '4', '4', '6', '0', '4',
        '5', '6', '1', '0', '0', '1', '7', '1', '6', '3', '0', '2', '1',
        '1', '7', '9', '0', '2', '6', '7', '8', '3', '9', '0', '4', '6',
        '7', '4', '6', '8', '0', '7', '8', '3', '1', '5', '7', '1', '7',
        '1', '1', '6', '3', '0', '2', '9', '3', '1', '1', '0', '4', '9',
        '2', '0', '0', '2', '0', '2', '7', '1', '8', '6', '4', '1', '6',
        '3', '4', '5', '9', '1', '3', '3', '

### Onehot Encode

In [17]:
from sklearn.preprocessing import OneHotEncoder

def one_hot_encode(X):
    encoder = OneHotEncoder(sparse_output=False)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    one_hot_encoded = encoder.fit_transform(X)
    return one_hot_encoded

In [18]:
y_encoded = one_hot_encode(y)
print(y_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


## Import Model

In [7]:
import sys
import os

# Get the absolute path of the src directory
sys.path.append(os.path.abspath('../')) 

from model.ffnn import FFNN

### 1. Testing Pengaruh Depth dan Width

#### a. Pengaruh Depth

##### -> Depth = 2 Layer

In [8]:
ffnn = FFNN(X, y_encoded, [784, 10], loss="mse", active=["sigmoid"], seed=69, weight="normal", mean=0.5, variance=1)
ffnn

Fully Connected Feed Forward Neural Network
> X = 500 x 784
> y = 500 x 1
> MLP of 1 Layers [
	Layer(label=Hidden-Layer-1, neurons=[
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N1)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N2)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N3)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N4)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N5)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N6)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N7)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N8)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N9)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N10)])]

In [ ]:
loss = ffnn.training(20, 0.005, 1, 3)

  0%|          | 0/1 [00:00<?, ?it/s]

Starting Epoch 0


100%|██████████| 1/1 [02:23<00:00, 143.03s/it]

Training Loss 0.9
Validation Loss 0.9



##### -> Depth = 3 Layer

In [10]:
ffnn = FFNN(X, y_encoded, [784,32, 10], loss="mse", active=["relu", "sigmoid"], seed=69, weight="normal", mean=0.5, variance=1)
ffnn

Fully Connected Feed Forward Neural Network
> X = 500 x 784
> y = 500 x 1
> MLP of 2 Layers [
	Layer(label=Hidden-Layer-1, neurons=[
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N1)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N2)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N3)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N4)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N5)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N6)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N7)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N8)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N9)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N10)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N11)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N12)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N13)
	Neuron(nin=784, activation=relu, label=Hidden-Layer-1_N14)
	Neuron(nin=784, activation=relu, la

In [ ]:
loss = ffnn.training(20, 0.005, 1, 3)

  0%|          | 0/1 [00:00<?, ?it/s]

Starting Epoch 0


100%|██████████| 1/1 [07:54<00:00, 474.20s/it]

Training Loss 0.9
Validation Loss 0.9



##### -> Depth = 4 Layer

In [14]:
ffnn = FFNN(X, y_encoded, [784,32,16,10], loss="mse", active=["sigmoid", "relu", "sigmoid"], seed=69, weight="normal", mean=0.5, variance=1)
ffnn

Fully Connected Feed Forward Neural Network
> X = 500 x 784
> y = 500 x 1
> MLP of 3 Layers [
	Layer(label=Hidden-Layer-1, neurons=[
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N1)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N2)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N3)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N4)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N5)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N6)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N7)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N8)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N9)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N10)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N11)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N12)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N13)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1

In [ ]:
loss = ffnn.training(20, 0.005, 1, 3)

  0%|          | 0/1 [00:00<?, ?it/s]

Starting Epoch 0


100%|██████████| 1/1 [08:26<00:00, 506.57s/it]

Training Loss 0.9
Validation Loss 0.9



#### b. Pengaruh Width

##### -> Width = 784, 26, 10, 10

In [19]:
ffnn = FFNN(X, y_encoded, [784,26,10,10], loss="mse", active=["sigmoid", "relu", "sigmoid"], seed=69, weight="normal", mean=0.5, variance=1)
ffnn

Fully Connected Feed Forward Neural Network
> X = 250 x 784
> y = 250 x 1
> MLP of 3 Layers [
	Layer(label=Hidden-Layer-1, neurons=[
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N1)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N2)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N3)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N4)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N5)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N6)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N7)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N8)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N9)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N10)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N11)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N12)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N13)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1

In [20]:
loss = ffnn.training(20, 0.005, 1, 2)

Starting Epoch 0


##### -> Width = 784, 32, 16, 10

In [21]:
ffnn = FFNN(X, y_encoded, [784, 32, 16, 10], loss="mse", active=["sigmoid", "relu", "sigmoid"], seed=69, weight="normal", mean=0.5, variance=1)
ffnn

Fully Connected Feed Forward Neural Network
> X = 250 x 784
> y = 250 x 1
> MLP of 3 Layers [
	Layer(label=Hidden-Layer-1, neurons=[
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N1)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N2)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N3)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N4)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N5)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N6)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N7)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N8)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N9)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N10)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N11)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N12)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N13)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1

In [22]:
loss = ffnn.training(20, 0.005, 1, 2)

Starting Epoch 0


##### -> Width = 784, 38, 22, 10

### 2. Testing Pengaruh Fungsi Aktivasi

### 3. Testing Pengaruh Inisialisasi Bobot

### 4. Perbandingan dengan library sklearn