In [1]:
import numpy as np
from sklearn.datasets import fetch_openml

X: np.ndarray  # input
y: np.ndarray  # target

# Load data from https://www.openml.org/search?type=data&sort=runs&id=554   
X, y = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False)

 
# MNIST: dataset of 28x28 pixel images of handwritten digits (0-9)
# Input: vector of 784 pixels (28x28)
# Target: number 0-9

In [2]:
X, y = X[:60], y[:60]
X.shape

(60, 784)

In [3]:
from sklearn.preprocessing import OneHotEncoder

def one_hot_encode(X):
    encoder = OneHotEncoder(sparse_output=False)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    one_hot_encoded = encoder.fit_transform(X)
    return one_hot_encoded

In [4]:
y_encoded = one_hot_encode(y)
print(y_encoded)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0.

In [5]:
import sys
import os

# Get the absolute path of the src directory
sys.path.append(os.path.abspath('../')) 

from model.ffnn import FFNN

In [6]:
ffnn = FFNN([784,14,10], loss="mse", regularization="none", active=["sigmoid", "sigmoid"], seed=69, weight="normal", mean=0.5, variance=1)
ffnn

Feed Forward Neural Network
> Layers: [784, 14, 10]
> MLP of 2 Layers [
	Layer(label=Hidden-Layer-1, neurons=[
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N1)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N2)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N3)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N4)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N5)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N6)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N7)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N8)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N9)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N10)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N11)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N12)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N13)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N14)])
	Layer(label=O

In [7]:
loss = ffnn.training(X, y_encoded, 20, 0.005, 5, 1)

  0%|          | 0/5 [00:00<?, ?it/s]

Starting Epoch 0


 20%|██        | 1/5 [00:19<01:18, 19.72s/it]

Training Loss: 0.8998256273586516
Validation Loss: 0.8998256271317335

Starting Epoch 1


 40%|████      | 2/5 [00:42<01:04, 21.63s/it]

Training Loss: 0.899825627129094
Validation Loss: 0.8998256269048126

Starting Epoch 2


 60%|██████    | 3/5 [01:07<00:46, 23.22s/it]

Training Loss: 0.8998256268995344
Validation Loss: 0.8998256266778906

Starting Epoch 3


 80%|████████  | 4/5 [01:32<00:23, 23.97s/it]

Training Loss: 0.8998256266699735
Validation Loss: 0.899825626450969

Starting Epoch 4


100%|██████████| 5/5 [01:58<00:00, 23.71s/it]

Training Loss: 0.8998256264404125
Validation Loss: 0.8998256262240474



In [8]:
ffnn_l1 = FFNN([784,14,10], loss="mse", regularization="l1", active=["sigmoid", "sigmoid"], seed=69, weight="normal", mean=0.5, variance=1)
ffnn_l1

Feed Forward Neural Network
> Layers: [784, 14, 10]
> MLP of 2 Layers [
	Layer(label=Hidden-Layer-1, neurons=[
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N1)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N2)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N3)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N4)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N5)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N6)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N7)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N8)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N9)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N10)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N11)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N12)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N13)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N14)])
	Layer(label=O

In [9]:
loss_l1 = ffnn_l1.training(X, y_encoded, 20, 0.005, 5, 1)

  0%|          | 0/5 [00:00<?, ?it/s]

Starting Epoch 0


 20%|██        | 1/5 [00:26<01:47, 26.86s/it]

Training Loss: 504.9818111099653
Validation Loss: 504.9818109789785

Starting Epoch 1


 40%|████      | 2/5 [00:56<01:24, 28.21s/it]

Training Loss: 504.98181097897583
Validation Loss: 504.98181084799126

Starting Epoch 2


 60%|██████    | 3/5 [01:21<00:53, 26.88s/it]

Training Loss: 504.98181084798597
Validation Loss: 504.98181071700486

Starting Epoch 3


 80%|████████  | 4/5 [01:49<00:27, 27.29s/it]

Training Loss: 504.9818107169969
Validation Loss: 504.9818105860164

Starting Epoch 4


100%|██████████| 5/5 [02:16<00:00, 27.21s/it]

Training Loss: 504.98181058600585
Validation Loss: 504.98181045503014



In [10]:
ffnn_l2 = FFNN([784,14,10], loss="mse", regularization="l2", active=["sigmoid", "sigmoid"], seed=69, weight="normal", mean=0.5, variance=1)
ffnn_l2

Feed Forward Neural Network
> Layers: [784, 14, 10]
> MLP of 2 Layers [
	Layer(label=Hidden-Layer-1, neurons=[
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N1)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N2)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N3)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N4)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N5)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N6)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N7)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N8)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N9)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N10)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N11)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N12)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N13)
	Neuron(nin=784, activation=sigmoid, label=Hidden-Layer-1_N14)])
	Layer(label=O

In [11]:
loss_l2 = ffnn_l2.training(X, y_encoded, 20, 0.005, 5, 1)

  0%|          | 0/5 [00:00<?, ?it/s]

Starting Epoch 0


 20%|██        | 1/5 [00:26<01:45, 26.30s/it]

Training Loss: 35.37707825447078
Validation Loss: 35.37707821396136

Starting Epoch 1


 40%|████      | 2/5 [00:53<01:19, 26.64s/it]

Training Loss: 35.377078213958725
Validation Loss: 35.37707817345191

Starting Epoch 2


 60%|██████    | 3/5 [01:23<00:56, 28.34s/it]

Training Loss: 35.377078173446634
Validation Loss: 35.3770781329423

Starting Epoch 3


 80%|████████  | 4/5 [01:51<00:28, 28.34s/it]

Training Loss: 35.377078132934386
Validation Loss: 35.377078092432754

Starting Epoch 4


100%|██████████| 5/5 [02:18<00:00, 27.70s/it]

Training Loss: 35.377078092422195
Validation Loss: 35.37707805192305



### 3. Testing Pengaruh Inisialisasi Bobot